// One-time helper: adds the needed commands to package.json and .gitignore.
// Usage:  node scripts/install-chess.mjs
import fs from "node:fs";

const pkgPath = "package.json";
const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
pkg.scripts = pkg.scripts ?? {};
pkg.scripts["chess:setup"] = "node scripts/chess-setup.mjs";
pkg.scripts.pieces = "node scripts/get-pieces.mjs";
const post = pkg.scripts.postinstall;
if (!post) pkg.scripts.postinstall = "node scripts/chess-setup.mjs";
else if (!post.includes("chess-setup")) pkg.scripts.postinstall = `${post} && node scripts/chess-setup.mjs`;
// "prebuild" runs automatically before "npm run build" (also on Vercel), independent of install-script settings.
const pre = pkg.scripts.prebuild;
if (!pre) pkg.scripts.prebuild = "node scripts/chess-setup.mjs";
else if (!pre.includes("chess-setup")) pkg.scripts.prebuild = `${pre} && node scripts/chess-setup.mjs`;
// "predev" runs automatically before "npm run dev": it restores the board styles and engine files
// even if a ZIP has overwritten them.
const pre2 = pkg.scripts.predev;
if (!pre2) pkg.scripts.predev = "node scripts/chess-setup.mjs";
else if (!pre2.includes("chess-setup")) pkg.scripts.predev = `${pre2} && node scripts/chess-setup.mjs`;
fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n");

let ignore = fs.existsSync(".gitignore") ? fs.readFileSync(".gitignore", "utf8") : "";
if (!ignore.includes("/public/engine/")) {
  ignore += "\n# generated by npm run chess:setup\n/public/engine/\n";
  fs.writeFileSync(".gitignore", ignore);
}
console.log("package.json and .gitignore are updated.");
